version: '2'
services:
  shell:
    container_name: shell
    image: shell:latest
    networks:
      - workspace_network
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
  db:
    container_name: db
    image: postgres
    networks:
      - workspace_network
    environment:
      - POSTGRES_PASSWORD=password
networks:
  workspace_network:
    driver: bridge
