version: '2'
services:
  workspace:
    container_name: workspace
    build:
      context: .
      dockerfile: workspace.Dockerfile
    command: [bundle, exec, rails, s, -p, '3000', -b, '0.0.0.0']
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@db/
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
